name: svr
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy=1.15.4
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - python=3.6.7
  - pytorch=1.0.0
  - pyyaml=3.13
  - scikit-image=0.14.1
  - scipy=1.1.0
  - tensorboardx=1.4
  - torchvision=0.2.1
  - tqdm=4.28.1
  - trimesh=2.37.7
  - pip=20.2.3
  - argparse
  - time
  - tqdm
  - yaml
  - pip:
    - opencv-python
    - errno
    - logging

